// Generated by scripts/generate-game-builds.cjs. Do not edit.
#pragma once

inline constexpr std::array<GeneratedBuild, 2> kGeneratedBuilds{{
    {"july-11-2026", 247845776ULL,
     "9E654AD49C4702D8F9FA4E38FD1110ABE657DD38926D4124B30C70E7D29ADFE8",
     Support::kCertified,
     BoardLayout{0xB093F68ULL, 0xB0B5BA8ULL, 0x8109060ULL, 0x8166090ULL}},
    {"patch-1-2026-07-16", 249801616ULL,
     "A048578530F7ED5967DF38803B63AD9B9F04FC71287F1E151C901A94AB240BFD",
     Support::kDiagnostic, std::nullopt},
}};
